name: Deploy to itch.io

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

env:
  GODOT_VERSION: 4.4.1

jobs:
  export-web:
    name: Web Export and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          godot-version: ${{ env.GODOT_VERSION }}
          include-templates: true

      - name: Web Build
        run: |
          mkdir -v -p builds/web
          godot --headless --verbose --export-release "HTML5" builds/web/index.html

      - name: Install Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Deploy to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          ./butler push builds/web downfallgames/brackeys25:html5